# Generated by Django 3.1.4 on 2021-02-07 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_image_id'),
        ('serviceNail', '0001_initial'),
        ('testimonial', '0001_initial'),
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='product_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='service_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceNail.serviceNail'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='testimonial_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testimonial.testimonial'),
        ),
    ]
