# Generated by Django 3.1.4 on 2021-02-07 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0002_auto_20210207_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='testimonial_ID',
        ),
    ]
