# Generated by Django 3.1.4 on 2021-02-07 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0003_remove_promotion_testimonial_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='product_ID',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='service_ID',
            new_name='service',
        ),
    ]
