# Generated by Django 3.1.5 on 2021-02-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceNail', '0006_auto_20210208_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicenail',
            name='service_description',
            field=models.TextField(max_length=200, verbose_name='Service Description'),
        ),
    ]
