# Generated by Django 3.1.4 on 2021-02-23 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceNail', '0008_auto_20210208_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicenail',
            name='duration',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Duration'),
        ),
    ]
