# Generated by Django 3.1.4 on 2021-02-07 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_image_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_ID',
        ),
    ]
