# Generated by Django 3.1.4 on 2021-02-07 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
        ('booking', '0002_auto_20210207_2339'),
        ('profileuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='booking_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.booking'),
        ),
        migrations.AddField(
            model_name='profile',
            name='role_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='role.role'),
        ),
    ]
