# Generated by Django 3.1.4 on 2021-02-07 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileuser', '0002_auto_20210207_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='booking_ID',
            new_name='booking',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='role_ID',
            new_name='role',
        ),
    ]
