# Generated by Django 3.1.4 on 2021-02-07 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileuser', '0003_auto_20210208_0009'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='profileuser',
        ),
    ]
