# Generated by Django 3.1.5 on 2021-02-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('slots_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='Slots ID')),
                ('time_slot', models.TimeField(verbose_name='Time Slot')),
            ],
            options={
                'db_table': 'slots',
            },
        ),
    ]
