# Generated by Django 3.1.4 on 2021-02-19 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0005_slots_date_slot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slots',
            old_name='date_slot',
            new_name='date',
        ),
    ]
