# Generated by Django 3.1.4 on 2021-02-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileuser', '0006_auto_20210218_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Contact No'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='home_address',
            field=models.CharField(blank=True, null=True, max_length=300, verbose_name='Home Address'),
        ),
    ]
