# Generated by Django 3.1.4 on 2021-02-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageFiles', '0003_auto_20210208_0020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagefiles',
            old_name='service_ID',
            new_name='service',
        ),
        migrations.AlterField(
            model_name='imagefiles',
            name='Image_ID',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Image ID'),
        ),
    ]
