# Generated by Django 3.1.4 on 2021-02-07 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0002_remove_testimonial_image_id'),
        ('product', '0003_remove_product_image_id'),
        ('serviceNail', '0002_remove_servicenail_image_id'),
        ('imageFiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefiles',
            name='product_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product'),
        ),
        migrations.AddField(
            model_name='imagefiles',
            name='service_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='serviceNail.servicenail'),
        ),
        migrations.AddField(
            model_name='imagefiles',
            name='testimonial_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testimonial.testimonial'),
        ),
    ]
