# Generated by Django 3.1.4 on 2021-02-07 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageFiles', '0002_auto_20210207_2334'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='imagefiles',
            table='imagefiles',
        ),
    ]
