# Generated by Django 3.1.4 on 2021-02-08 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageFiles', '0004_auto_20210208_0051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagefiles',
            options={'verbose_name_plural': 'ImageFiles'},
        ),
    ]
