# Generated by Django 3.1.4 on 2021-02-23 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0007_auto_20210223_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='slots',
            name='is_booked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
