# Generated by Django 3.1.4 on 2021-02-07 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0004_auto_20210208_0012'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testimonial',
            table='testimonial',
        ),
    ]
