# Generated by Django 3.1.4 on 2021-02-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0002_slots_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slots',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
