# Generated by Django 3.1.4 on 2021-02-18 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0003_auto_20210219_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slots',
            name='date',
        ),
    ]
