# Generated by Django 3.1.4 on 2021-02-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0004_remove_slots_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='slots',
            name='date_slot',
            field=models.DateField(blank=True, null=True),
        ),
    ]
