# Generated by Django 3.1.4 on 2021-02-23 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0006_auto_20210219_0805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slots',
            options={'verbose_name_plural': 'slots'},
        ),
    ]
