# Generated by Django 3.1.4 on 2021-02-07 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceNail', '0003_servicenail_image_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicenail',
            old_name='image_ID',
            new_name='image',
        ),
    ]
