# Generated by Django 3.1.5 on 2021-02-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceNail', '0007_auto_20210208_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicenail',
            name='service_ID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Service ID'),
        ),
        migrations.AlterField(
            model_name='servicenail',
            name='service_description',
            field=models.TextField(max_length=500, verbose_name='Service Description'),
        ),
    ]
