# Generated by Django 3.1.4 on 2021-02-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('Promotion_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='Promotion ID')),
                ('promo_type', models.CharField(max_length=30, verbose_name='Promotion Type')),
                ('promo_description', models.CharField(max_length=50, verbose_name='Promotion Description')),
                ('promo_start', models.DateTimeField(verbose_name='Promotion Start')),
                ('promo_end', models.DateTimeField(verbose_name='Promotion End')),
            ],
        ),
    ]
