# Generated by Django 3.1.5 on 2021-02-28 18:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0009_auto_20210228_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='code',
            field=models.CharField(blank=True, default=False, max_length=50, null=True, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_amt',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Discount'),
        ),
    ]
