# Generated by Django 3.1.4 on 2021-03-03 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0010_auto_20210301_0203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='code',
        ),
    ]
