# Generated by Django 3.1.4 on 2021-02-07 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imageFiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('testimonial_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='Testimonial ID')),
                ('image_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imageFiles.imageFiles')),
            ],
        ),
    ]
