# Generated by Django 3.1.4 on 2021-02-07 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='image_ID',
        ),
    ]
