# Generated by Django 3.1.4 on 2021-02-07 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0003_testimonial_image_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='image_ID',
            new_name='image',
        ),
    ]
