# Generated by Django 3.1.5 on 2021-02-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0006_auto_20210208_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='testimonial_ID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Testimonial ID'),
        ),
    ]
