# Generated by Django 3.1.4 on 2021-02-07 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20210208_0020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='product_ID',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='service_ID',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='user_ID',
            new_name='user',
        ),
    ]
