# Generated by Django 3.1.4 on 2021-02-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20210208_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_ID',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Booking ID'),
        ),
    ]
