# Generated by Django 3.1.5 on 2021-02-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20210208_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_ID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Booking ID'),
        ),
    ]
