# Generated by Django 3.1.4 on 2021-02-18 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0001_initial'),
        ('booking', '0008_auto_20210218_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slots.slots', verbose_name='Time of Booking'),
        ),
    ]
