# Generated by Django 3.1.5 on 2021-02-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageFiles', '0005_auto_20210208_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagefiles',
            old_name='service',
            new_name='service_ID',
        ),
        migrations.RemoveField(
            model_name='imagefiles',
            name='Image_For',
        ),
        migrations.AlterField(
            model_name='imagefiles',
            name='Image_ID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Image ID'),
        ),
    ]
