# Generated by Django 3.1.5 on 2021-02-21 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0007_auto_20210208_2353'),
        ('imageFiles', '0006_auto_20210208_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefiles',
            name='Promotion_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promotion.promotion'),
        ),
    ]
