# Generated by Django 3.1.5 on 2021-02-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileuser', '0004_auto_20210208_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='home_address',
            field=models.CharField(max_length=300, verbose_name='Home Address'),
        ),
    ]
