# Generated by Django 3.1.4 on 2021-02-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileuser', '0005_auto_20210208_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Contact No'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='home_address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Home Address'),
        ),
    ]
