# Generated by Django 3.1.4 on 2021-02-07 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_image_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_ID',
            new_name='image',
        ),
    ]
